### ISSUE TITLE
Update plenaries.json

### ISSUE THREAD

**Issue by sandervh14** [transparentdemocracy/backend#2]
I think the plenaries.json used in the hosted website on Amazon might not be the latest version from [voting-data](https://github.com/transparentdemocracy/voting-data).

There I see these plenaries (no filtering):

![image](https://github.com/transparentdemocracy/backend/assets/4201920/22c00521-421c-408c-8175-6fee7e057b29)

With my local host of the backend and the website, I see these:

![image](https://github.com/transparentdemocracy/backend/assets/4201920/bc5b0558-9834-47f9-95e0-827a9d3de8cf)

**Comment by GuidoDechamps** [comment]
of course, it was the version from monday. I focused on putting the application in the cloud and postponed using new data. One problem at a time :) Newest version just got deployed.
